services:
  djapp:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - DB_HOST=db
      - DB_NAME=postgresql
      - DB_USER=root
      - DB_PASS=database
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=postgresql
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=database
